name: "Design Issue"
description: "Report a UI/UX problem, visual inconsistency, or design flaw in the product"
title: "[DESIGN ISSUE] "
labels:
  - design
  - ux
  - triage
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        <!--
        Thank you for reporting a design issue!
        Please provide as much detail as possible so we can understand and address the problem.
        -->

  - type: textarea
    id: summary
    attributes:
      label: "Summary"
      description: "A brief, high-level description of the design issue."
      placeholder: "E.g. Button color doesn’t meet contrast requirements on mobile."
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: "Design Context"
      description: "Which page, screen, or component does this relate to? Provide navigation path or link."
      placeholder: "E.g. Settings > Profile > Change Avatar modal."
    validations:
      required: true

  - type: textarea
    id: expected_design
    attributes:
      label: "Expected Design"
      description: "How should it look or behave? Reference mocks, guidelines, or accessibility standards."
      placeholder: "E.g. Primary action buttons should use #005FCC with white text at 4.5:1 contrast."
    validations:
      required: true

  - type: textarea
    id: current_design
    attributes:
      label: "Current Design"
      description: "Describe what you’re seeing instead. Include screenshots or GIFs if available."
      placeholder: "E.g. The button is #2A2A2A with gray text, contrast ratio ~2:1."
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: "Platform / Device"
      description: "Where are you seeing this issue?"
      options:
        - Web – Desktop
        - Web – Mobile
        - iOS App
        - Android App
        - Other
      default: 0
    validations:
      required: true

  - type: input
    id: browser_or_version
    attributes:
      label: "Browser / App Version"
      description: "Browser name and version, or app build number."
      placeholder: "E.g. Chrome 112.0.5615.49 / iOS 1.4.0 (42)"
    validations:
      required: false

  - type: textarea
    id: steps_to_observe
    attributes:
      label: "Steps to Observe"
      description: "Step-by-step instructions to reproduce the design state."
      placeholder: |
        1. Open Dashboard  
        2. Click “New Project”  
        3. Observe primary button style
    validations:
      required: false

  - type: markdown
    attributes:
      value: "### Attachments"

  - type: checkboxes
    id: attachments
    attributes:
      label: "Include any of the following (optional):"
      options:
        - label: Screenshot
        - label: Annotated mockup
        - label: Link to design file (Figma, Sketch, etc.)
    validations:
      required: false

  - type: textarea
    id: additional_context
    attributes:
      label: "Additional Context"
      description: "Any other notes, links to tickets, or design doc references."
      placeholder: "E.g. Related to issue #123 in Figma."
    validations:
      required: false
